[build]
    command = "npm run build"
    publish = "build/"

[functions]
    directory = "functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    
[build.processing]
  ignore = "api/*"
